repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
      exclude: '^legacy/'
    # Run the formatter.
    - id: ruff-format
      exclude: '^legacy/'

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
    - id: mypy
      # additional_dependencies: [types-all]
      # args: [--config-file=pyproject.toml]
      exclude: '^(tests/|legacy/).*$'

